# Generated by Django 4.2.1 on 2023-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video_video',
        ),
    ]
